export const INGREDIENTS_GETTING_REQUEST: 'INGREDIENTS_GETTING_REQUEST' =
  'INGREDIENTS_GETTING_REQUEST';
export const INGREDIENTS_GETTING_REJECTED: 'INGREDIENTS_GETTING_REJECTED' =
  'INGREDIENTS_GETTING_REJECTED';
export const INGREDIENTS_GETTING: 'INGREDIENTS_GETTING' = 'INGREDIENTS_GETTING';
