export const LOGIN: 'LOGIN' = 'LOGIN';
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_REJECTED: 'LOGIN_REJECTED' = 'LOGIN_REJECTED';

export const LOGOUT: 'LOGOUT' = 'LOGOUT';
export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_REJECTED: 'LOGOUT_REJECTED' = 'LOGOUT_REJECTED';

export const REFRESH_TOKEN: 'REFRESH_TOKEN' = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' =
  'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_REJECTED: 'REFRESH_TOKEN_REJECTED' =
  'REFRESH_TOKEN_REJECTED';

export const CHECKING_AUTH: 'CHECKING_AUTH' = 'CHECKING_AUTH';
