export const REGISTRATION: 'REGISTRATION' = 'REGISTRATION';
export const REGISTRATION_REQUEST: 'REGISTRATION_REQUEST' =
  'REGISTRATION_REQUEST';
export const REGISTRATION_REJECTED: 'REGISTRATION_REJECTED' =
  'REGISTRATION_REJECTED';
