export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' =
  'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REJECTED: 'RESET_PASSWORD_REJECTED' =
  'RESET_PASSWORD_REJECTED';
export const RESETTING_PASSWORD: 'RESETTING_PASSWORD' = 'RESETTING_PASSWORD';
