export const USER_GETTING: 'USER_GETTING' = 'USER_GETTING';
export const USER_REQUEST: 'USER_REQUEST' = 'USER_REQUEST';
export const USER_REJECTED: 'USER_REJECTED' = 'USER_REJECTED';

export const USER_UPDATING: 'USER_UPDATING' = 'USER_UPDATING';
export const USER_UPDATING_REQUEST: 'USER_UPDATING_REQUEST' =
  'USER_UPDATING_REQUEST';
export const USER_UPDATING_REJECTED: 'USER_UPDATING_REJECTED' =
  'USER_UPDATING_REJECTED';

export const IS_USER_AUTH: 'IS_USER_AUTH' = 'IS_USER_AUTH';
